apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami-grpc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whereami-grpc
  template:
    metadata:
      labels:
        app: whereami-grpc
        version: v1
    spec:
      serviceAccountName: whereami-grpc-ksa
      containers:
      - name: whereami-grpc
        image: gcr.io/google-samples/whereami:v1.2.1
        ports:
          - name: grpc
            containerPort: 9090
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9090"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9090"]
          initialDelaySeconds: 10
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: BACKEND_ENABLED
            valueFrom:
              configMapKeyRef:
                name: whereami-grpc-configmap
                key: BACKEND_ENABLED
          - name: BACKEND_SERVICE
            valueFrom:
              configMapKeyRef:
                name: whereami-grpc-configmap
                key: BACKEND_SERVICE
          - name: METADATA
            valueFrom:
              configMapKeyRef:
                name: whereami-grpc-configmap
                key: METADATA
          - name: ECHO_HEADERS
            valueFrom:
              configMapKeyRef:
                name: whereami-grpc-configmap
                key: ECHO_HEADERS
          - name: GRPC_ENABLED
            valueFrom:
              configMapKeyRef:
                name: whereami-grpc-configmap
                key: GRPC_ENABLED